### ISSUE TITLE
Wrong index if loop-option is enabled

### ISSUE THREAD

**Issue by hahrens** [smashingboxes/OwlCarousel2#1203]
The Event "changed.owl.carousel" has a wrong/invalid index in event.item.index when loop is enabled.

> Object { count=5,  index=3}
> Object { count=5,  index=4}
> Object { count=5,  index=5}
> Object { count=5,  index=6}
> Object { count=5,  index=7}

I have the following Options:
> animateOut: "fadeOut",
> items: 1,
> itemsDesktop: false,
> itemsDesktopSmall: false,
> itemsTablet: false,
> itemsTabletSmall: false,
> itemsMobile: false,
> singleItem : true,
> itemsScaleUp: true,
> pagination: false,
> navigation: false,
> autoplay: true,
> loop: true,
> autoplayTimeout: 5000,
> slideSpeed: 300

**Comment by lbineau** [comment]
:+1: Same issue with loop: true option (1 or multiple items)

**Comment by jbrialon** [comment]
+1 I always have issues when I use the loop:true option

**Comment by nicolasRdr** [comment]
It's also blocking for me, in the same condition (loop:true)

**Comment by diesonne** [comment]
same issue here when loop: true
if the carousel is set to autoplay the index starts at 3
if the carousel is not set to autoplay the index starts at 2
not yet sure if this is consistent, if so, easily fixed in my own code

**Comment by louiswalch** [comment]
Here is a JSFIDDLE showing the error:
http://jsfiddle.net/louiswalch/rt3qkpb6/

**Comment by ohepworthbell** [comment]
Yes, I am getting this issue too.

It seems that when loop is set to true, Owl Carousel adds in "clone" slides and then mistakenly includes these when calculating the index. I have a carousel with 4 full-width slides. When loop is set to false, the index.count returns 0,1,2,3 (correct) and when loop is set to true, it returns 3,4,5,6,3,4,5,6... etc. (incorrect)

**Comment by ohepworthbell** [comment]
A quick fix for now (that might be worth implementing into the actual Owl Carousel) is:

`var current_slide_in_loop = e.page.index - (e.relatedTarget._clones.length / 2)`

**Comment by Rouche** [comment]
Fix above does not seem to work with version 2.1.6.

I had to use this formula:
owlEvent.item.index - (owlEvent.relatedTarget.clones().length / 2)

**Comment by Serjster** [comment]
Will this ever be fixed? It's setting the active class to the wrong item in my case :(

**Comment by Rouche** [comment]
```
options.onChanged(
    (owlEvent: OwlCarouselEvent, scope: ScopeCarrousel) => {
        if (!owlEvent.item.index) {
            return;
        }
        //Bug  index loop : https://github.com/OwlCarousel2/OwlCarousel2/issues/1203
        scope.item = owlEvent.item.index;
        if(scope.options.loop) { //We are using loop option
            var tempFix: number = scope.itemCourant - (owlEvent.relatedTarget.clones().length / 2)
            if(tempFix >= 0) {
                scope.itemCourant = tempFix;
            }
        }
        scope.currentItem++;
        
        //Do stuff with correct index
        ...
    }
);
```

**Comment by Serjster** [comment]
Thanks for your post, this got me all excited but to no avail... I am now getting this:
> ERROR Error: Uncaught (in promise): TypeError: this.homeCarousel.options.onChanged is not a function

I get my `homeCarousel` like this:
> @ViewChild('homeCarousel') homeCarousel: OwlCarousel
template:
><owl-carousel #homeCarousel
package.json
>"ng2-owl-carousel": "^0.1.15",

**Comment by Serjster** [comment]
For NG2 wrapped carousel... you can do this:
(I'm doing it in the ngOnInit)

```
(<any>this.homeCarousel.$owlChild).el.nativeElement.onchange = function(e) { 
            setTimeout(() => {
                var item  = e.item;
                var owl = e.relatedTarget;

                let itemCount = 0;
                for(let i = 0; i < owl.$stage[0].childNodes.length; i++)
                {
                    owl.$stage[0].childNodes[i].className = owl.$stage[0].childNodes[i].className.replace(' active', '');
                    
                    if (owl.$stage[0].childNodes[i].className.indexOf('clone') == -1)
                    {
                        if (itemCount == item.index - 1)
                            owl.$stage[0].childNodes[i].className += ' active';
                        else
                            itemCount++;
                    }
                }
            }, 100);
        }
```

The problem remains still that the initially loaded frame is not getting the active applied to it... only on the second round trip it does.

**Comment by Serjster** [comment]
For this who care, again this is for the NG2 wrapper of OwlCarousel 2, here you go:

 ```
 ngOnInit() {
        setTimeout(() => this.fixCourouselActiveBug() , 100);
    }
    private fixCourouselActiveBug() {
        let owl: any;
        for(let key in (<any>this.homeCarousel.$owlChild).el.nativeElement)
        {
            if (typeof (<any>this.homeCarousel.$owlChild).el.nativeElement[key]['owl.carousel'] != 'undefined')
            {
                owl = (<any>this.homeCarousel.$owlChild).el.nativeElement[key]['owl.carousel'];
                break;
            }
        }
        
        this.fixChildNodes(owl);
        
        (<any>this.homeCarousel.$owlChild).el.nativeElement.onchange = () => {
            setTimeout(() => this.fixChildNodes(owl), 100);
        }
    }
    private fixChildNodes(owl: any, fixAmount: number = 2) {
        let itemCount = 0;
        for(let i = 0; i < owl.$stage[0].childNodes.length; i++)
        {
            owl.$stage[0].childNodes[i].className = owl.$stage[0].childNodes[i].className.replace(' active', '');
            
            if (owl.$stage[0].childNodes[i].className.indexOf('clone') == -1)
            {
                if (itemCount == owl._current - fixAmount)
                    owl.$stage[0].childNodes[i].className += ' active';
                else
                    itemCount++;
            }
        };
    }
```

It's definitely a jimmy-rig, but it lets me keep going...

**Comment by pttsky** [comment]
I managed to *sync two infinite owl carousels* based on [your pretty good idea](https://github.com/OwlCarousel2/OwlCarousel2/issues/1203#issuecomment-229763204), thank you @Rouche!
 
I simplified your code (removed `if (index > 0)` thing) because synced carousel remained still when going from the last slide to first.

```
const loop = true, $carousels = $('.synced-carousels');
$carousels.owlCarousel({
    /* whatever config */
    loop: loop
}).on('translated.owl.carousel', function(e) {
    let targetIndex = e.item.index;
    if (loop) {
         targetIndex -=  e.relatedTarget.clones().length / 2;
    }
   $carousels.not(this).trigger('to.owl.carousel', [targetIndex]);
})
```

**Comment by ivanmart** [comment]
You guys are awesome, thanks. One remark is that `/ 2` won't work as expected when active item is the first item in the carousel and you're dragging in the reverse direction so the next active item will be the last item in the carousel. In this situation there'll be **+1** clone before index, so the only way we have is to **get the exact number of clones before index**. And there's a useful jQuery function `prevAll` for it. Also 
`$carousels.not(this)` means all other carousels on the page which is not what I needed, so I trigger strictly the previous carousel as it's main to this one. Here's the code:

```
.on('changed.owl.carousel', function (e) {
    var index = e.item.index;
    var offset = $(e.target).find('.active:first').prevAll('.cloned').length;
    $(e.target.parentElement.previousElementSibling).trigger('to.owl.carousel', index-offset);
});
```

**Comment by daria2303** [comment]
This is still not working properly if displayed item is not 1. Numbers repeat in my case :(

**Comment by GavinJaynes** [comment]
I'm still experiencing the issue

**Comment by don-dev** [comment]
++1 still experiencing issue

**Comment by costheme** [comment]
I'm having the same issue, in place of 4 existing items i see 8 cloned. Any fix?

**Comment by yunusga** [comment]
```js
function fixOwlCurrentIdx(event) {
  let current = (event.item.index + 1) - event.relatedTarget._clones.length / 2;
  let itemsCount = event.item.count;

  if (current > itemsCount || current == 0) {
    current = itemsCount - (current % itemsCount);
  }
  
  return current - 1;
}
```
Example: [jsfiddle.net/yunusga/4zvpns6j/](https://jsfiddle.net/yunusga/4zvpns6j/)

**Comment by mayurjadav77** [comment]
function syncPosition2(el) {
            if (syncedSecondary) {
                //var number = el.item.index;
                //bigimage.data("owl.carousel").to(number, 100, true);

                let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
                let itemsCount = el.item.count;

                if (current > itemsCount || current == 0) {
                    current = itemsCount - (current % itemsCount);
                }
                bigimage.data("owl.carousel").to(current - 1, 100, true);
            }
        }

**Comment by mayurjadav77** [comment]
> 
> 
> function syncPosition2(el) {
> if (syncedSecondary) {
> //var number = el.item.index;
> //bigimage.data("owl.carousel").to(number, 100, true);
> 
> ```
>             let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
>             let itemsCount = el.item.count;
> 
>             if (current > itemsCount || current == 0) {
>                 current = itemsCount - (current % itemsCount);
>             }
>             bigimage.data("owl.carousel").to(current - 1, 100, true);
>         }
>     }
> ```



> 
> 
> Here is a JSFIDDLE showing the error:
> http://jsfiddle.net/louiswalch/rt3qkpb6/1/

function syncPosition2(el) {
            if (syncedSecondary) {
                //var number = el.item.index;
                //bigimage.data("owl.carousel").to(number, 100, true);

                let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
                let itemsCount = el.item.count;

                if (current > itemsCount || current == 0) {
                    current = itemsCount - (current % itemsCount);
                }
                bigimage.data("owl.carousel").to(current - 1, 100, true);
            }
        }

**Comment by mayurjadav77** [comment]
> 
> 
> Here is a JSFIDDLE showing the error:
> http://jsfiddle.net/louiswalch/rt3qkpb6/1/

function syncPosition2(el) {
            if (syncedSecondary) {
                //var number = el.item.index;
                //bigimage.data("owl.carousel").to(number, 100, true);

                let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
                let itemsCount = el.item.count;

                if (current > itemsCount || current == 0) {
                    current = itemsCount - (current % itemsCount);
                }
                bigimage.data("owl.carousel").to(current - 1, 100, true);
            }
        }

**Comment by mayurjadav77** [comment]
function syncPosition2(el) {
            if (syncedSecondary) {
                //var number = el.item.index;
                //bigimage.data("owl.carousel").to(number, 100, true);

                let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
                let itemsCount = el.item.count;

                if (current > itemsCount || current == 0) {
                    current = itemsCount - (current % itemsCount);
                }
                bigimage.data("owl.carousel").to(current - 1, 100, true);
            }
        }

**Comment by mayurjadav77** [comment]
function syncPosition2(el) {
            if (syncedSecondary) {
                let current = (el.item.index + 1) - el.relatedTarget._clones.length / 2;
                let itemsCount = el.item.count;

                if (current > itemsCount || current == 0) {
                    current = itemsCount - (current % itemsCount);
                }
                bigimage.data("owl.carousel").to(current - 1, 100, true);
            }
        }

**Comment by szymsza** [comment]
Any updates on this? Quite an important issue, yet still open 4 years later

**Comment by ohepworthbell** [comment]
@szymsza the project has now been depreciated, so you'll need to either find an actively maintained fork, or migrate to a different slider - [TinySlider](https://github.com/ganlanyuan/tiny-slider) seems the common recommendation (as mentioned in the updated [README.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/README.md))
